# Generated by Django 3.2.5 on 2021-07-14 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurants',
            name='favorite',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='user',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='visits',
        ),
        migrations.CreateModel(
            name='RestaurantStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('favorite', models.BooleanField(default=False)),
                ('visits', models.IntegerField(default=0)),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_stats', to='restaurants.restaurants')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
