# Generated by Django 3.2.5 on 2021-07-14 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20210714_0620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantstats',
            old_name='restaurant_id',
            new_name='restaurant',
        ),
        migrations.RenameField(
            model_name='restaurantstats',
            old_name='user_id',
            new_name='user',
        ),
    ]
