# Generated by Django 3.2.5 on 2021-07-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_auto_20210714_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='lng',
            field=models.FloatField(),
        ),
    ]
